[theme]
primaryColor = "#003E1F"             # Phthalo green (core MythMatch color)
backgroundColor = "#0E0F11"          # Dark cathedral stone
secondaryBackgroundColor = "#1C1D21" # Scroll chamber shade
textColor = "#FFFFFF"                # White, for contrast
font = "Serif"                       # Matches Cinzel + parchment aesthetic
